name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Ideas welcome! Describe what you'd like TAVS to do.

  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: "Describe the feature or improvement you'd like to see."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New visual state
        - New theme preset
        - New terminal support
        - New agent support
        - CLI improvement
        - Title/spinner feature
        - Configuration option
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: "When would you use this? What problem does it solve?"
    validations:
      required: true

  - type: input
    id: terminal
    attributes:
      label: Terminal (if relevant)
      placeholder: "Ghostty / iTerm2 / Kitty / etc."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: "Any workarounds or alternatives you've tried?"
