#!/bin/bash
# ==============================================================================
# TAVS - Terminal Agent Visual Signals — Configuration Wizard
# ==============================================================================
# Interactive configuration for TAVS visual signals.
#
# Orchestrates the configuration wizard by sourcing step modules:
#   Step 1: Operating mode (static, dynamic, preset)
#   Step 2: Theme preset selection
#   Step 3: Light/dark mode auto-detection
#   Step 4: ASCII faces (anthropomorphising)
#   Step 5: Stylish backgrounds (images)
#   Step 6: Terminal title mode
#   Step 7: Palette theming (OSC 4)
#
# Creates user configuration in ~/.tavs/user.conf
# ==============================================================================

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TAVS_ROOT="$( cd "$SCRIPT_DIR/../.." && pwd )"
CONFIG_DIR="$HOME/.tavs"
USER_CONFIG="$CONFIG_DIR/user.conf"

# Source required modules (relative to project root)
source "$TAVS_ROOT/src/core/themes.sh"
source "$TAVS_ROOT/src/core/theme-config-loader.sh"

# Source configuration wizard modules (same directory as this script)
source "$SCRIPT_DIR/configure-utilities.sh"
source "$SCRIPT_DIR/configure-step-operating-mode.sh"
source "$SCRIPT_DIR/configure-step-theme-preset.sh"
source "$SCRIPT_DIR/configure-step-light-dark-mode.sh"
source "$SCRIPT_DIR/configure-step-ascii-faces.sh"
source "$SCRIPT_DIR/configure-step-backgrounds.sh"
source "$SCRIPT_DIR/configure-step-terminal-title.sh"
source "$SCRIPT_DIR/configure-step-palette-theming.sh"

# ==============================================================================
# PREVIEW
# ==============================================================================

show_preview() {
    print_section "Configuration Preview"

    echo "  Settings to be saved:"
    echo ""
    echo -e "  ${BOLD}Operating Mode:${NC}      $SELECTED_MODE"
    [[ "$SELECTED_MODE" == "preset" ]] && echo -e "  ${BOLD}Theme Preset:${NC}        $SELECTED_PRESET"
    echo -e "  ${BOLD}Auto Dark Mode:${NC}      $SELECTED_LIGHT_DARK_SWITCHING"
    [[ "$SELECTED_FORCE_MODE" != "auto" ]] && echo -e "  ${BOLD}Force Mode:${NC}          $SELECTED_FORCE_MODE"
    echo -e "  ${BOLD}ASCII Faces:${NC}         $SELECTED_FACE_ENABLED"
    if [[ "$SELECTED_FACE_ENABLED" == "true" ]]; then
        echo -e "  ${BOLD}Face Theme:${NC}          $SELECTED_FACE_THEME"
        echo -e "  ${BOLD}Face Position:${NC}       $SELECTED_FACE_POSITION"
    fi
    echo -e "  ${BOLD}Stylish Backgrounds:${NC} $SELECTED_STYLISH_ENABLED"
    if [[ "$SELECTED_STYLISH_ENABLED" == "true" ]]; then
        echo -e "  ${BOLD}Backgrounds Dir:${NC}     $SELECTED_STYLISH_DIR"
    fi
    echo -e "  ${BOLD}Title Mode:${NC}          $SELECTED_TITLE_MODE"
    if [[ "$SELECTED_TITLE_MODE" == "prefix-only" ]]; then
        echo -e "  ${BOLD}Title Fallback:${NC}      $SELECTED_TITLE_FALLBACK"
    fi
    if [[ "$SELECTED_TITLE_MODE" == "full" ]]; then
        echo -e "  ${BOLD}Spinner Style:${NC}       $SELECTED_SPINNER_STYLE"
        echo -e "  ${BOLD}Eye Mode:${NC}            $SELECTED_SPINNER_EYE_MODE"
        echo -e "  ${BOLD}Session Identity:${NC}    $SELECTED_SESSION_IDENTITY"
    fi
    echo -e "  ${BOLD}Palette Theming:${NC}     $SELECTED_PALETTE_MODE"
    if [[ "$SELECTED_CREATE_ALIAS" == "true" ]]; then
        echo -e "  ${BOLD}Create Claude Alias:${NC} Yes (256-color mode)"
    fi
    echo ""

    # Color preview
    echo "  Color preview (current terminal may not show background changes):"
    echo ""

    # Load preview colors
    local preview_proc preview_perm preview_comp preview_idle
    if [[ "$SELECTED_MODE" == "preset" ]] && [[ -n "$SELECTED_PRESET" ]]; then
        source "$TAVS_ROOT/src/themes/${SELECTED_PRESET}.conf" 2>/dev/null || true
        preview_proc="$DARK_PROCESSING"
        preview_perm="$DARK_PERMISSION"
        preview_comp="$DARK_COMPLETE"
        preview_idle="$DARK_IDLE"
    else
        preview_proc="$COLOR_PROCESSING"
        preview_perm="$COLOR_PERMISSION"
        preview_comp="$COLOR_COMPLETE"
        preview_idle="$COLOR_IDLE"
    fi

    echo -e "  Processing: ${YELLOW}$preview_proc${NC}"
    echo -e "  Permission: ${RED}$preview_perm${NC}"
    echo -e "  Complete:   ${GREEN}$preview_comp${NC}"
    echo -e "  Idle:       ${MAGENTA}$preview_idle${NC}"
    echo ""
}

# ==============================================================================
# SAVE CONFIGURATION
# ==============================================================================

save_configuration() {
    print_section "Saving Configuration"

    # Create config directory
    mkdir -p "$CONFIG_DIR"

    # Generate config file
    cat > "$USER_CONFIG" << EOF
#!/bin/bash
# ==============================================================================
# TAVS - Terminal Agent Visual Signals — User Configuration
# ==============================================================================
# Generated by configure.sh on $(date)
# Edit this file to customize your settings.
#
# This file is loaded AFTER global and agent configs, so your settings
# here override everything else.
# ==============================================================================

# Operating Mode: static, dynamic, or preset
THEME_MODE="$SELECTED_MODE"
EOF

    if [[ "$SELECTED_MODE" == "preset" ]]; then
        cat >> "$USER_CONFIG" << EOF

# Theme preset (when THEME_MODE="preset")
THEME_PRESET="$SELECTED_PRESET"
EOF
    fi

    cat >> "$USER_CONFIG" << EOF

# Enable light/dark mode switching based on system appearance
ENABLE_LIGHT_DARK_SWITCHING="$SELECTED_LIGHT_DARK_SWITCHING"
EOF

    if [[ "$SELECTED_FORCE_MODE" != "auto" ]]; then
        cat >> "$USER_CONFIG" << EOF

# Force light or dark mode: auto, light, dark
FORCE_MODE="$SELECTED_FORCE_MODE"
EOF
    fi

    cat >> "$USER_CONFIG" << EOF

# ASCII Faces (Anthropomorphising)
ENABLE_ANTHROPOMORPHISING="$SELECTED_FACE_ENABLED"
FACE_THEME="$SELECTED_FACE_THEME"
FACE_POSITION="$SELECTED_FACE_POSITION"

# Stylish Backgrounds (Images)
ENABLE_STYLISH_BACKGROUNDS="$SELECTED_STYLISH_ENABLED"
EOF

    if [[ "$SELECTED_STYLISH_ENABLED" == "true" ]] && [[ -n "$SELECTED_STYLISH_DIR" ]]; then
        cat >> "$USER_CONFIG" << EOF
STYLISH_BACKGROUNDS_DIR="$SELECTED_STYLISH_DIR"
EOF
    fi

    cat >> "$USER_CONFIG" << EOF

# Terminal Title Mode
# Options: "full" (TAVS owns all), "prefix-only" (preserve user titles), "skip-processing" (let Claude handle), "off" (no titles)
TAVS_TITLE_MODE="$SELECTED_TITLE_MODE"
EOF

    if [[ "$SELECTED_TITLE_MODE" == "prefix-only" ]]; then
        cat >> "$USER_CONFIG" << EOF

# Title Fallback (for TAVS_TITLE_MODE="prefix-only")
# Options: "path", "session-path", "path-session", "session"
TAVS_TITLE_FALLBACK="$SELECTED_TITLE_FALLBACK"
EOF
    fi

    if [[ "$SELECTED_TITLE_MODE" == "full" ]]; then
        cat >> "$USER_CONFIG" << EOF

# Spinner Configuration (for TAVS_TITLE_MODE="full")
TAVS_SPINNER_STYLE="$SELECTED_SPINNER_STYLE"
TAVS_SPINNER_EYE_MODE="$SELECTED_SPINNER_EYE_MODE"
TAVS_SESSION_IDENTITY="$SELECTED_SESSION_IDENTITY"
EOF
    fi

    cat >> "$USER_CONFIG" << EOF

# Palette Theming (OSC 4)
# Options: "false" (disabled), "auto" (if not TrueColor), "true" (always)
ENABLE_PALETTE_THEMING="$SELECTED_PALETTE_MODE"
EOF

    # Create Claude alias if requested
    if [[ "$SELECTED_CREATE_ALIAS" == "true" ]]; then
        local shell_rc=""
        if [[ -f "$HOME/.zshrc" ]]; then
            shell_rc="$HOME/.zshrc"
        elif [[ -f "$HOME/.bashrc" ]]; then
            shell_rc="$HOME/.bashrc"
        fi

        if [[ -n "$shell_rc" ]]; then
            # Check if alias already exists
            if ! grep -q "alias claude=" "$shell_rc" 2>/dev/null; then
                cat >> "$shell_rc" << 'ALIAS_EOF'

# Claude Code with 256-color mode for TAVS palette theming
# Added by TAVS configure.sh
alias claude='TERM=xterm-256color COLORTERM= claude'
ALIAS_EOF
                echo ""
                echo -e "  ${GREEN}Added Claude alias to:${NC} $shell_rc"
                print_info "Run 'source $shell_rc' or restart your terminal to use it."
            else
                echo ""
                echo -e "  ${YELLOW}Claude alias already exists in:${NC} $shell_rc"
            fi
        fi
    fi

    echo ""
    echo -e "  ${GREEN}Configuration saved to:${NC}"
    echo -e "  ${BOLD}$USER_CONFIG${NC}"
    echo ""
    echo -e "  ${DIM}Your settings will apply to all agents (Claude, Gemini, etc.)${NC}"
    echo -e "  ${DIM}Restart your terminal session to see the changes.${NC}"
}

# ==============================================================================
# MAIN FLOW
# ==============================================================================

main() {
    print_header

    # Show current config if exists
    if [[ -f "$USER_CONFIG" ]]; then
        echo -e "  ${YELLOW}Existing configuration found.${NC}"
        echo -e "  ${DIM}$USER_CONFIG${NC}"
        echo ""
        if ! confirm "Reconfigure?"; then
            echo ""
            echo -e "  ${DIM}No changes made.${NC}"
            exit 0
        fi
    fi

    select_operating_mode
    select_theme_preset
    select_auto_dark_mode
    select_faces
    select_stylish_backgrounds
    select_title_mode
    select_palette_theming

    show_preview

    if confirm "Save this configuration?"; then
        save_configuration
        echo ""
        echo -e "${GREEN}${BOLD}Configuration complete!${NC}"
    else
        echo ""
        echo -e "${YELLOW}Configuration cancelled. No changes made.${NC}"
    fi

    echo ""
}

# ==============================================================================
# COMMAND LINE OPTIONS
# ==============================================================================

show_help() {
    echo "TAVS - Terminal Agent Visual Signals — Configuration Wizard"
    echo ""
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -h, --help      Show this help message"
    echo "  -l, --list      List available theme presets"
    echo "  -c, --current   Show current configuration"
    echo "  -r, --reset     Reset to default configuration"
    echo ""
    echo "Run without options for interactive configuration."
}

list_presets() {
    echo "Available theme presets:"
    echo ""
    if [[ -d "$TAVS_ROOT/src/themes" ]]; then
        for conf in "$TAVS_ROOT/src/themes"/*.conf; do
            local name
            name=$(basename "$conf" .conf)
            local desc
            desc=$(grep -m1 "^# Description:" "$conf" 2>/dev/null | sed 's/# Description: //' || echo "")
            echo "  $name"
            [[ -n "$desc" ]] && echo "    $desc"
        done
    else
        echo "  No presets found."
    fi
}

show_current() {
    if [[ -f "$USER_CONFIG" ]]; then
        echo "Current user configuration:"
        echo "File: $USER_CONFIG"
        echo ""
        cat "$USER_CONFIG"
    else
        echo "No user configuration found."
        echo "Run $0 to create one."
    fi
}

reset_config() {
    if [[ -f "$USER_CONFIG" ]]; then
        if confirm "Delete user configuration and reset to defaults?"; then
            rm "$USER_CONFIG"
            echo "Configuration reset to defaults."
        fi
    else
        echo "No user configuration to reset."
    fi
}

case "${1:-}" in
    -h|--help)
        show_help
        ;;
    -l|--list)
        list_presets
        ;;
    -c|--current)
        show_current
        ;;
    -r|--reset)
        reset_config
        ;;
    *)
        main "$@"
        ;;
esac
